name:                chime
version:             0.1.0.0
github:              "jeremyschlatter/chime"
author:              "Jeremy Schlatter"
copyright:           "2020 Jeremy Schlatter"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/jeremyschlatter/chime#readme>

dependencies:
- base >= 4.7 && < 5
- base-prelude

default-extensions:
- BlockArguments
- ConstraintKinds
- DeriveFunctor
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GADTs
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- PatternSynonyms
- QuantifiedConstraints
- QuasiQuotes
- RankNTypes
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- ViewPatterns

ghc-options:
- -O2
- -Wall
# https://github.com/commercialhaskell/rio/blob/e878b3d/rio/README.md#ghc-options
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - bytestring
  - containers
  - directory
  - file-embed
  - filepath
  - haskeline
  - megaparsec
  - microlens
  - microlens-th
  - microlens-mtl
  - mtl
  - parser-combinators
  - random
  - template-haskell
  - text
  - time
  - transformers

executables:
  chime:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - chime

tests:
  chime-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chime
    - bytestring
    - hspec
    - HUnit
    - random
    - raw-strings-qq
    - template-haskell
    - text
    - time
    - transformers
