name:                chime
version:             0.1.0.0
github:              "jeremyschlatter/chime"
author:              "Jeremy Schlatter"
copyright:           "2019 Jeremy Schlatter"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/jeremyschlatter/chime#readme>

dependencies:
- base >= 4.7 && < 5
- base-prelude

default-extensions:
- BlockArguments
- ConstraintKinds
- DeriveFunctor
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- PatternSynonyms
- QuantifiedConstraints
- QuasiQuotes
- RankNTypes
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- ViewPatterns

ghc-options:
- -Wall
- -O2

library:
  source-dirs: src
  dependencies:
  - bytestring
  - containers
  - directory
  - file-embed
  - filepath
  - haskeline
  - lens
  - megaparsec
  - mtl
  - parser-combinators
  - template-haskell
  - text
  - time
  - transformers

executables:
  chime:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - chime
  playground:
    main:         Main.hs
    source-dirs:  playground
    ghc-options:
    - -rtsopts
    dependencies:
    - chime
    - scotty
    - text

tests:
  chime-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chime
    - hspec
    - HUnit
    - template-haskell
    - time
    - transformers
