name:                chime-playground
version:             0.1.0.0
github:              "jeremyschlatter/chime"
author:              "Jeremy Schlatter"
copyright:           "2020 Jeremy Schlatter"

description:         Please see the README on GitHub at <https://github.com/jeremyschlatter/chime#readme>

dependencies:
- base >= 4.7 && < 5
- base-prelude

default-extensions:
- BlockArguments
- ConstraintKinds
- DeriveFunctor
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GADTs
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- NumericUnderscores
- NoImplicitPrelude
- PatternSynonyms
- QuantifiedConstraints
- QuasiQuotes
- RankNTypes
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- ViewPatterns

ghc-options:
- -O2
- -Wall
# https://github.com/commercialhaskell/rio/blob/e878b3d/rio/README.md#ghc-options
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

executables:
  playground:
    main:         Main.hs
    source-dirs:  .
    ghc-options:
    - -rtsopts
    dependencies:
    - chime
    - aeson
    - base64
    - bytestring
    - bytestring-delta
    - cryptohash-sha256
    - google-oauth2-jwt
    - http-types
    - http-conduit
    - scotty
    - text
    - zstd
