name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache deps
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: stack
    - name: Run tests
      run: CHIME_INCLUDE_SLOW_TESTS=1 stack test --ghc-options=-Werror
